# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'podTest' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod ‘AFNetworking’, ‘~>3.1.0’
pod 'PLPlayerKit'
  # Pods for podTest

  target 'podTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
